### ISSUE TITLE
fcp: errno : libffs.c(709) : (code=12) __ffs_buffer => Cannot allocate memory (errno=12)

### ISSUE THREAD

**Issue by alvintpwang** [open-power/ffs#6]
# Symptom

use fcp to dump PNOR image, the content of VERSION partition are all 0xFF. 
ex:
cd ~/op-build/output/images/
~/op-build/output/host/usr/bin/fcp -R -o 0 palmetto.pnor:VERSION VERSION.txt
cat VERSION.txt
# Reproduce steps:

Run op-build in an machine with few memory, in my case it's 2G memory. I increased my VM memory from 2G to 4G and that fixed this issue. 
# Build log
###### ########################/home/alvin/op-build/output/host/usr/powerpc64-buildroot-linux-gnu/sysroot/hostboot_build_images//buildpnor.pl --pnorOutBin /home/alvin/op-build/output/host/usr/powerpc64-buildroot-linux-gnu/sysroot/pnor/palmetto.pnor --pnorLayout /home/alvin/op-build/output/build/openpower-pnor-ed1682e10526ebd85825427fbf397361bb0e34aa/defaultPnorLayoutSingleSide.xml --binFile_HBD /home/alvin/op-build/output/host/usr/powerpc64-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//PALMETTO_HB.targeting.bin.ecc --binFile_SBE /home/alvin/op-build/output/host/usr/powerpc64-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//venice_sbe.img.ecc --binFile_SBEC /home/alvin/op-build/output/host/usr/powerpc64-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//centaur_sbec_pad.img.ecc --binFile_WINK /home/alvin/op-build/output/host/usr/powerpc64-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//p8.ref_image.hdr.bin.ecc --binFile_HBB /home/alvin/op-build/output/host/usr/powerpc64-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//hostboot.header.bin.ecc --binFile_HBI /home/alvin/op-build/output/host/usr/powerpc64-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//hostboot_extended.header.bin.ecc --binFile_HBRT /home/alvin/op-build/output/host/usr/powerpc64-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//hostboot_runtime.header.bin.ecc --binFile_HBEL /home/alvin/op-build/output/host/usr/powerpc64-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//hbel.bin.ecc --binFile_GUARD /home/alvin/op-build/output/host/usr/powerpc64-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//guard.bin.ecc --binFile_PAYLOAD /home/alvin/op-build/output/images/skiboot.lid --binFile_BOOTKERNEL /home/alvin/op-build/output/images/zImage.epapr --binFile_NVRAM /home/alvin/op-build/output/host/usr/powerpc64-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//nvram.bin.ecc --binFile_MVPD /home/alvin/op-build/output/host/usr/powerpc64-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//mvpd_fill.bin.ecc --binFile_DJVPD /home/alvin/op-build/output/host/usr/powerpc64-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//djvpd_fill.bin.ecc --binFile_CVPD /home/alvin/op-build/output/host/usr/powerpc64-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//cvpd.bin.ecc --binFile_ATTR_TMP /home/alvin/op-build/output/host/usr/powerpc64-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//attr_tmp.bin.ecc --binFile_ATTR_PERM /home/alvin/op-build/output/host/usr/powerpc64-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//attr_perm.bin.ecc --binFile_OCC /home/alvin/op-build/output/host/usr/powerpc64-buildroot-linux-gnu/sysroot/occ/occ.bin.ecc --binFile_FIRDATA /home/alvin/op-build/output/host/usr/powerpc64-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//firdata.bin.ecc --binFile_CAPP /home/alvin/op-build/output/host/usr/powerpc64-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//cappucode.bin.ecc --binFile_VERSION /home/alvin/op-build/output/host/usr/powerpc64-buildroot-linux-gnu/sysroot/openpower_version/openpower-pnor.version.txt --fpartCmd "fpart" --fcpCmd "fcp"

TRACE:  main::loadPnorLayout: metadata: imageSize = 33554432, blockSize=4096, arrangement = A-D-B, numOfSides: 1, sideSize: 33554432, tocSize: 32768
TRACE: A-D-B: side:A HBB:32927744, primaryTOC:0, backupTOC:33521664, golden: no
TRACE: Done checkSpaceConstraints
TRACE: createPnorPartition:: 0
TRACE: createPnorImg:: 0
TRACE: createPnorPartition:: 33521664
TRACE: createPnorImg:: 33521664
TRACE: fpart --target /home/alvin/op-build/output/host/usr/powerpc64-buildroot-linux-gnu/sysroot/pnor/palmetto.pnor --partition-offset 0 --add --offset 33521664 --size 32768 --name BACKUP_PART --flags 0x0
TRACE: fpart --target /home/alvin/op-build/output/host/usr/powerpc64-buildroot-linux-gnu/sysroot/pnor/palmetto.pnor --partition-offset 33521664 --add --offset 0 --size 32768 --name BACKUP_PART --flags 0x0
TRACE: fillPnorImage:: 0
fcp: errno : libffs.c(709) : (code=12) __ffs_buffer => Cannot allocate memory (errno=12)
fcp: errno : libffs.c(709) : (code=12) __ffs_buffer => Cannot allocate memory (errno=12)
fcp: errno : libffs.c(709) : (code=12) __ffs_buffer => Cannot allocate memory (errno=12)
fcp: errno : libffs.c(709) : (code=12) __ffs_buffer => Cannot allocate memory (errno=12)
fcp: errno : libffs.c(709) : (code=12) __ffs_buffer => Cannot allocate memory (errno=12)
fcp: errno : libffs.c(709) : (code=12) __ffs_buffer => Cannot allocate memory (errno=12)
fcp: errno : libffs.c(709) : (code=12) __ffs_buffer => Cannot allocate memory (errno=12)
fcp: errno : libffs.c(709) : (code=12) __ffs_buffer => Cannot allocate memory (errno=12)
fcp: errno : libffs.c(709) : (code=12) __ffs_buffer => Cannot allocate memory (errno=12)
fcp: errno : libffs.c(709) : (code=12) __ffs_buffer => Cannot allocate memory (errno=12)
fcp: errno : libffs.c(709) : (code=12) __ffs_buffer => Cannot allocate memory (errno=12)
fcp: errno : libffs.c(709) : (code=12) __ffs_buffer => Cannot allocate memory (errno=12)
fcp: errno : libffs.c(709) : (code=12) __ffs_buffer => Cannot allocate memory (errno=12)
fcp: errno : libffs.c(709) : (code=12) __ffs_buffer => Cannot allocate memory (errno=12)ls 
fcp: errno : libffs.c(709) : (code=12) __ffs_buffer => Cannot allocate memory (errno=12)
fcp: errno : libffs.c(709) : (code=12) __ffs_buffer => Cannot allocate memory (errno=12)
fcp: errno : libffs.c(709) : (code=12) __ffs_buffer => Cannot allocate memory (errno=12)
fcp: errno : libffs.c(709) : (code=12) __ffs_buffer => Cannot allocate memory (errno=12)
fcp: errno : libffs.c(709) : (code=12) __ffs_buffer => Cannot allocate memory (errno=12)
fcp: errno : libffs.c(709) : (code=12) __ffs_buffer => Cannot allocate memory (errno=12)
fcp: errno : libffs.c(709) : (code=12) __ffs_buffer => Cannot allocate memory (errno=12)
/usr/bin/install /home/alvin/op-build/output/host/usr/powerpc64-buildroot-linux-gnu/sysroot/pnor/"palmetto.pnor" /home/alvin/op-build/output/images
# if this config has an UPDATE_FILENAME defined, create a 32M (1/2 size)
# image that only updates the non-golden side

if [ """" != "" ]; then dd if=/home/alvin/op-build/output/host/usr/powerpc64-buildroot-linux-gnu/sysroot/pnor/"palmetto.pnor" of=/home/alvin/op-build/output/host/usr/powerpc64-buildroot-linux-gnu/sysroot/pnor/"" bs=32M count=1; /usr/bin/install /home/alvin/op-build/output/host/usr/powerpc64-buildroot-linux-gnu/sysroot/pnor/"" /home/alvin/op-build/output/images; fi
make: Leaving directory `/home/alvin/op-build/buildroot'

**Comment by ghost** [comment]
Fixed in https://github.com/open-power/ffs/commit/6bd1a1fe3ec12e177278303e6db0c79b1a14b631
